######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 6 14:01:59 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . ..
INCLUDEPATH += . ..

# Input
HEADERS += ../pktnkju.hpp
SOURCES += ../main.cpp ../pktnkju.cpp
